### ISSUE TITLE
Can't find SublimeZilla.sublime-settings

### ISSUE THREAD

**Issue by kampiamodikuesto** [ment4list/SublimeZilla#15]
i'm try to use sublimeZilla 3 on osx 10.11
i have to installa manually (i put the sublime-text package into Packages folder) because i can't find the package into Package Controll. If i click on tools--> SublimeZilla i get this advice:

"File sitemanager.xml not found. Is FileZilla installed? 

If the sitemanager.xml file is located elsewhere please see https://github.com/ment4list/SublimeZilla#alternate-locations"

i think this i due to the fact that i use filezilla with sitemanager.xml as a symlink, the original is on my cloud folder (google drive). For this way i try to edit this file /Packages/User/SublimeZilla.sublime-settings to add the original path manually but i can't find this file under /Packages/User

can someone help me to understand what's the problem?

**Comment by ment4list** [comment]
Hi, you can simply create the file _SublimeZilla.sublime-settings_ in the _/Packages/User_ folder if it doesn't exist.

**Comment by kampiamodikuesto** [comment]
Great works:)

For OSX [10.11] and sublime text 3:
SublimeZilla.sublime-settings:

{ 
	"filezilla_db_path": "/Users/[User Name]/[PathTo]/sitemanager.xml" 
}
