### ISSUE TITLE
sitemanager.xml not found and SublimeZilla.sublime-settings missing

### ISSUE THREAD

**Issue by teomor** [ment4list/SublimeZilla#17]
On Mac OS Sierra I can't import my FileZilla servers. The alternate location instructions didn't help. It says "A new file will have been created in /Packages/User/SublimeZilla.sublime-settings and it will contain a path to the default FileZilla DB" but I don't have that file..

**Comment by ment4list** [comment]
You need to create the `/Packages/User/SublimeZilla.sublime-settings` file yourself and add the following:

`{
    "filezilla_db_path" : "/Users/[OSXUSERNAME]/.config/filezilla/sitemanager.xml"
}`

**Comment by teomor** [comment]
Awesome! I thought about that myself, but I'm new on Mac and I have no idea what I'm doing :)
Thanks a lot!

PS: Maybe the instructions need to be more clear, just in case some other people are struggling with this :)

**Comment by ment4list** [comment]
Great, glad it's working!

And yeah, I've just added this issue to the _readme_ as this has come up a few times now. 

Thanks for giving it a try! :)
