### ISSUE TITLE
IndexError: list index out of range on Windows 7 + ST3

### ISSUE THREAD

**Issue by urbgimtam** [ment4list/SublimeZilla#18]
Couldn't execute the plugin in Windows 7 with ST3.

Error was `IndexError: list index out of range` on the `if User[0].firstChild is not None:`, line 208.

Had to update to `if len(User) > 0 and User[0].firstChild is not None:` for it to work.
Just to let you know. Great plug, thanks.

**Comment by Varindien** [comment]
if LocalDir[0].firstChild is not None:

AND
if  RemoteDir[0].firstChild is not None:

adding len(XXX) > 0 do the trick

EDIT: Issues is certainly due to Folder in filezilla software : to_be_check
