### ISSUE TITLE
Confused about the status of this package

### ISSUE THREAD

**Issue by TonyGravagno** [ment4list/SublimeZilla#21]
I've spent hours with this plugin. It looks like it was never finished.

1. "SFTP" isn't the correct foldername for the package over Windows, it's "FileZilla SFTP Import".
1. default config doesn't ever seem to be written, requires manual save using the first config created for a project.
1. sftp-config.json for a project needs to be written manually, OK, but it's not read back anywhere.
1. The check for self.set_sftp_config() is made in server_chosen after it already determines that the config file doesn't exist and it bails.
1. If we save a file in a project under projectroot\folder1\folder2\name, I'm not sure from looking at the code that the file is uploaded to remotepath\folder1\folder2\name.

So, what's up with this plugin? Or ... please tell me where I'm missing the details noted here.
(Might be an opportunity to update the README.)

If I'm correct about all of that, I've made a number of changes to accommodate those issues, and I will submit a PR at some point when I've verified the changes. But for now it looks like it's going to be a while before I get that done.

Thanks!

**Comment by ment4list** [comment]
I think maybe you're missing the use case? This is a helper plugin to import saved FileZilla FTP settings for use with the SFTP plugin.

I considered it "finished" in the sense that it works for my use case. It's perhaps not the best optimised or well written. It also isn't as _actively_ maintained as more popular plugins.

Let me address your individual concerns:

1. That's correct. It's the folder on all platforms. [SFTP](https://wbond.net/sublime_packages/sftp) is a separate plugin
2. Will have to look into that
3. SFTP config is created to be used with the above mentioned SFTP plugin
4. As can probably be gathered from the code, this is my first stab at a Sublime Plugin and Python so it isn't the best..
5. Better have a look at [SFTP's docs](https://wbond.net/sublime_packages/sftp/usage)

Sorry for the misunderstanding and thanks for the helpful comments. :)

**Comment by TonyGravagno** [comment]
LOL well that's embarrassing. :blush: 
OK, Sorry for my confusion - and thanks for your cordial response.
